config/routes.rb
TodoChunks::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :chunks, only: [:create, :destroy]
  
  root  'static_pages#home'

  get '/chunks/:id/:action/:action_id' => 'chunks#action'
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/chunk.rb
class Chunk < ActiveRecord::Base
	belongs_to :user
	
	default_scope -> { order('created_at ASC') }
	validates :user_id, presence: true
	validates :short_desc, presence: true, length: { maximum: 256 }
end

app/models/chunk_status.rb
class ChunkStatus < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :chunks
	
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
	uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/chunks_controller.rb
class ChunksController < ApplicationController
	before_action :signed_in_user, only: [:create, :delete, :action]

	def index
	end

	def create
		@chunk = current_user.chunks.build(chunk_params)
		
		# XXX fix this to obtrain the correct default value for a new chunk
		@chunk.chunk_status_id = 0
		
		if @chunk.save
			flash[:success] = "Chunk posted!"
			redirect_to @current_user
		else
			render 'static_pages/home'
		end
	end

	def destroy
		# set status of the chunk to deleted
		# create an undo link
		flash[:warning] = "Placeholder message: Chunk not yet deleted! click to undo"

		# redirect to the chunk list
		redirect_to root_url
	end

	def action
		# determine what action to perform

		# create a chunk_status_log entry with the old, new status and start and endtime

		# update the status of the chunk	
		flash[:success] = "Perform " + params['action_id'] + " on chunk " + params['id']

		# redirect to the chunk list
		redirect_to @current_user
	end

	def undo
	end

	private
		def chunk_params
			params.require(:chunk).permit(:short_desc)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			# Sign the user in and redirect to the user's show page.
			sign_in user
			redirect_back_or user
		else
			flash[:error] = 'Invalid email/password combination' # Not quite right!
			redirect_to root_path	# Create an error message and re-render the homepage with signup form
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:edit, :update, :show]
	before_action :correct_user,   only: [:edit, :update, :show]

	def show
		@user = User.find(params[:id])
		@chunk = current_user.chunks.build if signed_in?
		@chunks = @user.chunks
	end
	
	def new
		@user = User.new
	end

	def edit
	end

	def update
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			sign_in @user
			redirect_to @user
		else
			render 'edit'
		end
	end

	def index
		redirect_to root_path
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to Chunks!"
			redirect_to @user
		else
			render 'new'
		end
	end

	private
		def user_params
			params.require(:user).permit(:name, :email, :password,
											:password_confirmation)
		end

		# Before filters
		def correct_user
			@user = User.find(params[:id])
			unless current_user?(@user)
				flash[:notice] = "Trying to access wrong user."
				redirect_to(root_path) 
			end
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def current_user=(user)
		@current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url
	end

	def signed_in_user
		unless signed_in?
			store_location
			flash[:notice] = "Please sign in."
			redirect_to root_path
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/chunks/_chunk.html.erb
<li>
	<input type="checkbox" id="optionsCheckbox" value="option1">
	<span class="content"><%= chunk.short_desc %></span>
	<a href="/chunks/<%= chunk.id %>/action/close"><i class="icon-ok pull-right"></i></a>
	<%= link_to chunk_path, :method => :delete  do %>
		<i class="icon-remove pull-right"></i>
	<% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Get things done with Chunks  | <%= yield(:title) %></title>
	<%= stylesheet_link_tag    "application", media: "all",
	"data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- <script src="js/respond.js"></script> XXXX -->
</head>
<body class="preview" id="top" data-spy="scroll" data-target=".subnav" data-offset="80">
	<!-- Navbar ================================================== -->
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="brand" href=<%= root_path %>>Chunks</a>
				<div class="nav-collapse collapse" id="main-menu">
					<ul class="nav" id="main-menu-left">
						<li><a id="swatch-link" href="/contact">Contact</a></li>
						<li><a id="swatch-link" href="/help">FAQ</a></li>
					</ul>
					<ul class="nav pull-right" id="main-menu-right">
						<li>
							<% if signed_in? %>
								<li id="fat-menu" class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Signed in as <%= current_user.name %> <b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
								<li><%= link_to "Chunk list", current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li>
								  <%= link_to "Sign out", signout_path, method: "delete" %>
								</li>
								</ul>
								</li>
							<% else %>
								<li><%= link_to "Sign up", signup_path %></li>
							<% end %>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/shared/_chunk_form.html.erb
<%= form_for(@chunk) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="input-append">
	<%= f.text_field :short_desc, placeholder: "To do chunk..." %>
	<%= f.submit "Create", class: "btn btn-primary" %>
</div>
</form>
<script type="text/javascript" language="JavaScript">
	document.getElementById('chunk_short_desc').focus();
</script>
<% end %>

app/views/shared/_chunk_list.html.erb
<% if @user.chunks.any? %>
	<ol class="chunks">
		<%= render @chunks %>
	</ol>
<% else %>
	<h3>Nothing to do!</h3>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= link_to "view my profile", current_user %>
</span>
<span>
	<%= pluralize(current_user.chunks.count, "chunk") %>
</span>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="span4">
	<h3>Chunks | Contact</h3>
	<address>
		<strong>Mark Braspenning</strong><br>
		Eindhoven, The Netherlands<br>
		<a href="mailto:#">info@chunks.eu</a><br>
	</address>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'FAQ') %>
	<div class="span12">
		<h3>Chunks | FAQ</h3>
		<div class ="accordion" id="accordion2">
			<div class="accordion-group">
				<div class="accordion-heading">
					<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
						How does Chunks work?								
					</a>
				</div>
				<div id="collapseOne" class="accordion-body collapse">
					<div class="accordion-inner">
					By constantly asking if a chunk can be done by one/a few person(s) within a few days, else break it down into smaller chunks.
					</div>
				</div>
			</div>
			<div class="accordion-group">
				<div class="accordion-heading">
					<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
					How is this different from brainstorm and mind mapping tools?
					</a>
				</div>
				<div id="collapseTwo" class="accordion-body collapse">
					<div class="accordion-inner">
					On the surface, the method used closely resembles mindmapping tools. Under the hood, the goal goes well beyond brainstorming and will help you to finish your project.
					</div>
				</div>
			</div>
			<div class="accordion-group">
				<div class="accordion-heading">
					<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
					Why include a task list?
					</a>
				</div>
				<div id="collapseThree" class="accordion-body collapse">
					<div class="accordion-inner">
					This project started out as a simple list to keep track of tasks, but soon I found out that defining the tasks was a more pressing issue. With clear targets we'll end up with more finished projects, hence the shift to defining the tasks, while still keeping track of them.
					</div>
				</div>
			</div>
			<div class="accordion-group">
				<div class="accordion-heading">
					<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
					Can I "get things done" with this system?
					</a>
				</div>
				<div id="collapseFour" class="accordion-body collapse">
					<div class="accordion-inner">
					As the task list is roughly based on the ideas presented by David Allen in his book <a href="http://en.wikipedia.org/wiki/Getting_Things_Done" target="_new">Getting Things Done</a>, this should work out really well. Also splitting tasks in manageable chunks originates from this book. 
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<!-- Masthead	================================================== -->
<header class="jumbotron subhead" id="overview">
	<div class="row">
		<div class="span12">
			<h1>Get Things Done with Chunks!</h1>
			<p class="lead">
				Chunks homepage
			</p>
		</div>
	</div>
</header>

<% if !signed_in? %>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(:session, url: sessions_path) do |f| %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>
		<br>

		<%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
		<% end %>

		<p>New user? <%= link_to "Sign up now!", signup_path %></p>
	</div>
</div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>
      <br>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <br>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
	<%= gravatar_for @user %>
	<%= @user.name %>
</h1>

<div class="span8">
<%= render 'shared/chunk_form' %>
<%= render 'shared/chunk_list' %>
</div>